services:
  srback:
    image: backend:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT= 8085


  srfront:
    image: frontend:0.0.1
    build: .
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - /appfront/node_modules
      - ./frontend:/appfront
